frontend:
  image: my-frontend:latest
  replicas: 1
  service:
    type: ClusterIP
    port: 80

backend:
  image: my-backend:latest
  replicas: 1
  service:
    type: ClusterIP
    port: 8080

database:
  image: postgres:15
  replicas: 1
  service:
    type: ClusterIP
    port: 5432
  storage:
    size: 1Gi
    storageClassName: standard
