apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-app.fullname" . }}-backend
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app: backend
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.port }}
