apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-app.fullname" . }}-database
spec:
  replicas: {{ .Values.database.replicas }}
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: {{ .Values.database.image }}
          ports:
            - containerPort: {{ .Values.database.service.port }}
          volumeMounts:
            - name: db-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: {{ include "my-app.fullname" . }}-db-pvc
